### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by mcepl** [tsyesika/Muon#12]
After the installation when running `./src/muon` I got this:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/home/matej/archiv/knihovna/repos/Muon/lib/python2.7/site-packages/xudd/hive.py", line 96, in run
    self.workloop()
  File "/home/matej/archiv/knihovna/repos/Muon/lib/python2.7/site-packages/xudd/hive.py", line 121, in workloop
    self._process_actor_messages()
  File "/home/matej/archiv/knihovna/repos/Muon/lib/python2.7/site-packages/xudd/hive.py", line 170, in _process_actor_messages
    actor.handle_message(message)
  File "/home/matej/archiv/knihovna/repos/Muon/lib/python2.7/site-packages/xudd/actor.py", line 22, in wrapper
    result = func(self, message)
  File "/home/matej/archiv/knihovna/repos/Muon/lib/python2.7/site-packages/xudd/actor.py", line 85, in handle_message
    result = message_handler(message)
  File "/home/matej/archiv/knihovna/repos/Muon/src/pump/main.py", line 37, in setup
    client_type="native"
TypeError: __init__() got an unexpected keyword argument 'client_name'
```

**Comment by moggers87** [comment]
PyPump's API has changed since Muon was written, patches welcome ☺

**Comment by mcepl** [comment]
`rm -rf ~/repos/Muon` is too much easier.
